name: Build, Test, and Deploy to Azure

on:
  push:
    branches:
      - main 

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '7' 

    - name: Restore dependencies
      run: dotnet restore src/WalletTool.UI/WalletTool.UI.csproj

    - name: Build
      run: dotnet build src/WalletTool.UI/WalletTool.UI.csproj --no-restore

    - name: Restore test project dependencies
      run: dotnet restore tests/WalletTool.UI.Tests.Unit/WalletTool.UI.Tests.Unit.csproj

    - name: Test
      run: dotnet test tests/WalletTool.UI.Tests.Unit/WalletTool.UI.Tests.Unit.csproj --no-build --verbosity normal

  deploy_to_azure:
    needs: build_and_test 
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Deploy to Azure
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ secrets.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: src/WalletTool.UI

